markdown: kramdown
title: SodaPop
tagline: A fast simulator for population dynamics and molecular evolution.
description: A fast, versatile forward-time simulator for large-scale population dynamics and molecular evolution.
show_downloads: "true"
baseurl: "/SodaPop"
author :
    name : Louis Gauthier
    email : louis.gauthier@umontreal.ca
    github : louisgt
    url : https://github.com/louisgt