markdown: kramdown
permalink: /_posts/:year/:month/:day/:title
title: SodaPop
description: A fast, versatile forward-time simulator for large-scale population dynamics and molecular evolution.
show_downloads: "true"
baseurl: "/SodaPop"
