theme: jekyll-theme-cayman
title: SodaPop
description: A fast, versatile forward-time simulator for large-scale population dynamics and molecular evolution.
show_downloads: "true"
path: https://github.com/louisgt/SodaPop
